### ISSUE TITLE
Increasing batch_size not rize GPU memory utilization in training wav2vec2 base model

### ISSUE THREAD

**Issue by 32r81b** [facebookresearch/fairseq#4922]
Good day!

I'm trying to train model from scratch with instruction https://github.com/facebookresearch/fairseq/blob/main/examples/wav2vec/README.md#train-a-wav2vec-20-base-model:

I have 2 A100 GPUS and want to use all availible power. I add strings "batch_size: 200" and "num_workers: 20" to "dataset" section in wav2vec2_base_librispeech.yaml as:

```
dataset:
  batch_size: 200
  num_workers: 20
  max_tokens: 1400000
  skip_invalid_size_inputs_valid_test: true
```

I expect that GPU memory usage increase, but it not happened.  I have 20-30% memory utilization with batch_size = 4, 200 or 2000.

![image](https://user-images.githubusercontent.com/8361949/209554332-247d544d-7855-4277-a445-fba92f5a33a1.png)

How to point to "fairseq-hydra-train" to use bigger batches?

Thanks for any help!
