### ISSUE TITLE
Cannot run GAN training for wav2vec-U 2.0 

### ISSUE THREAD

**Issue by EomSooHwan** [facebookresearch/fairseq#5283]
### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?

I tried to reproduce wav2vec-U 2.0 with python 3.8. When I ran the GAN training script from [README](https://github.com/facebookresearch/fairseq/tree/main/examples/wav2vec/unsupervised#generative-adversarial-training-gan), however, I got the following message.

```
File "/mnt/hdd/esyoon/anaconda3/envs/iclr24_38/lib/python3.8/site-packages/hydra/_interal/core_plugins/importlib_resources_config_source.py", line 72, in available
    ret = resources.is_resource(self.path, "__init__.py") # type: ignore
AttributeError: module 'importlib_resources' has no attribute 'is_resource'
```

I assumed this was because some kind of version mismatch inside hydra and python, so I changed my environment to python 3.9. However, this time I have encountered the following error.

```
File "/mnt/hdd/esyoon/anaconda3/envs/iclr24/lib/python3.9/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex # set and OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigKeyError: Key 'submitit_folder' not in 'BasicLauncherConf'
        full_key: hydra.launcher.submitit_folder
        reference_type=Optional[BasicLauncherConf]
        object_type=BasicLauncherConf
```

I think this has something to do with `config/gan/w2vu2.yaml` hydra part:

```
hydra:
  job:
    config:
      override_dirname:
        kv_sep: ':'
        item_sep: '__'
        exclude_keys:
          - run_config
          - distributed_training.distributed_port
          - common.user_dir
          - task.data
          - task.kenlm_path
          - task.text_data
          - model.generator_layers
          - task.labels
          - task.force_model_seed
  sweep:
    dir: /checkpoint/${env:USER}/${env:PREFIX}/${hydra.job.config_name}/${hydra.job.override_dirname}
    subdir: ${hydra.job.num}
  launcher:
    submitit_folder: ${hydra.sweep.dir}
    timeout_min: 3000
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 120
    nodes: 1
    name: ${env:PREFIX}_${hydra.job.config_name}
    partition: devlab,learnlab,learnfair,scavenge
    comment: intern_endding_soon
    constraint: volta32gb
    max_num_timeout: 30
```

I am assuming I need to edit the sweep directory but I have not confidence.

My question is:
(1) To run the code in python 3.8, how should I fix the problem above?
(2) What should I do with `hydra.sweep.dir` ?

#### What have you tried?

Changed python version
searched for relevant issues in fairseq and hydra

#### What's your environment?

 - fairseq Version (e.g., 1.0 or main): main
 - PyTorch Version (e.g., 1.0) 2.0.1+cu117
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source?
 - Build command you used (if compiling from source): `pip install --editable ./`
 - Python version: 3.8 or 3.9
 - CUDA/cuDNN version: 11.6
 - GPU models and configuration: Quadro RTX 8000
 - Any other relevant information:
