### ISSUE TITLE
Problem using multiple yaml files with hydra

### ISSUE THREAD

**Issue by henrycharlesworth** [facebookresearch/fairseq#5370]
#### What is your question?
I am trying to use hydra to configure an experiment, and I want to have separate yaml files for the model, task etc but am running into some issues. I have created an example model class and registered it ("simple_lstm_enc_dec), and I am running:

`hydra-train.py --config-name test --config-dir config`

In the config folder I have a 'test.yaml' as follows:

```
model:
  _name: simple_lstm_enc_dec
  encoder_embed_dim: 64

task:
  _name: translation
  data: ...
criterion: cross_entropy
```

and this works fine. But what I want to do is to separate out the model parameters into a different yaml file. So what I have tried is to create a folder "config/model" and created a file inside called "simple_lstm_encoder_decoder.yaml" with the following:

```
_name: simple_lstm_enc_dec
encoder_embed_dim: 64
```

and then I change my test.yaml file to:

```
defaults:
  model: simple_lstm_encoder_decoder

task:
  _name: translation
  data: ...
criterion: cross_entropy
```

But I get an error:

"Cannot merge DictConfig with ListConfig
	full_key: 
	reference_type=Optional[Dict[Union[str, Enum], Any]]
	object_type=FairseqConfig"

I have been trying to follow this: https://github.com/facebookresearch/fairseq/blob/main/docs/hydra_integration.md
but it only mentions this possibility without giving a full example.
What is the correct way to do what I'm trying to achieve here? Thanks in advance.
